# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Rahul Sharma
email: juristrahulsharma@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://naweel1496.github.io" # the base hostname & protocol for your site
twitter_username: 
github_username:  rahulsharma87

permalink:  none

# Build settings
markdown: kramdown

# /:categories/:title.html
permalink: none

# URLS
link_to:
  facebook:        https://www.facebook.com/rahul.sharman.5
  github:          https://github.com/rahulsharma87
  twitter:         
  linkedin:        
  github_profile_pic: http://www.khmertimeskh.com/wp-content/uploads/2017/08/privacy.jpg

theme: jekyll-theme-slate
